roles = list(reversed(['Urban Studies and Planning', 'Undeclared', 'Theatre Studies', 'Technical Systems Management',
                       'Teacher Education: Spanish (K-12)',
                       'Teacher Education: Kinesiology - Physical Education (K-12)',
                       'Teacher Education: German (K-12)', 'Teacher Education: French (K-12)',
                       'Systems Engineering and Design',
                       'Sustainable Design', 'Supply Chain Management', 'Studio Art (BFA)', 'Studio Art (BA)',
                       'Strategic Business Development and Entrepreneurship', 'Statistics and Computer Science',
                       'Statistics',
                       'Stage Management', 'Speech and Hearing Science', 'Special Education', 'Spanish',
                       'Sound Design and Technology', 'Sociology', 'Social Work', 'Slavic Studies',
                       'Secondary Education: Social Studies', 'Secondary Education: Physics',
                       'Secondary Education: Mathematics',
                       'Secondary Education: English', 'Secondary Education: Earth Science',
                       'Secondary Education: Chemistry',
                       'Secondary Education: Biology', 'Secondary Education', 'Scenic Technology', 'Scenic Design',
                       'Russian, East European, and Eurasian Studies', 'Religion', 'Recreation, Sport and Tourism',
                       'Public Policy & Law', 'Psychology', 'Portuguese', 'Political Science',
                       'Policy, International Trade & Development', 'Plant Biotechnology', 'Physics, Engineering',
                       'Physics',
                       'Photography', 'Philosophy', 'Organizational and Community Leadership', 'Operations Management',
                       'Nuclear, Plasma, and Radiological Engineering', 'Natural Resources and Environmental Sciences',
                       'Musicology',
                       'Music Voice Performance', 'Music Open Studies', 'Music Instrumental Performance',
                       'Music Education (K-12)',
                       'Music Composition', 'Music', 'Molecular and Cellular Biology',
                       'Middle Grades Education (Grades 5-8)',
                       'Metropolitan Food and Environmental Systems', 'Media and Cinema Studies',
                       'Mechanical Engineering',
                       'Mathematics and Computer Science', 'Mathematics', 'Materials Science and Engineering',
                       'Marketing',
                       'Management', 'Lyric Theatre', 'Linguistics', 'Lighting Design and Technology',
                       'Learning and Education Studies', 'Latina/Latino Studies', 'Landscape Architecture',
                       'Latin American Studies',
                       'Kinesiology', 'Journalism', 'Jazz Performance', 'Italian', 'Interdisciplinary Studies',
                       'Integrative Biology',
                       'Information Systems', 'Information Sciences', 'Industrial Engineering', 'Industrial Design',
                       'Human Nutrition', 'Human Development and Family Studies', 'Hospitality Management',
                       'History of Art',
                       'History', 'Health Sciences, Interdisciplinary', 'Graphic Design', 'Global Studies',
                       'Germanic Studies',
                       'Geology', 'Geography and Geographic Information Science', "Gender and Women's Studies",
                       'French',
                       'Food Science & Human Nutrition', 'Food Science', 'Financial Planning',
                       'Finance in Agri-Business',
                       'Finance',
                       'Farm Management', 'Environmental Economics & Policy', 'English', 'Engineering Mechanics',
                       'Elementary Education (Grades 1-6)', 'Electrical Engineering', 'Economics',
                       'Econometrics and Quantitative Economics', 'East Asian Languages and Cultures',
                       'Earth, Society, and Environmental Sustainability', 'Early Childhood Education (Birth-Grade 2)',
                       'Dietetics',
                       'Dance (BFA)', 'Dance (BA)', 'Crop Sciences', 'Creative Writing',
                       'Costume Design and Technology',
                       'Consumer Economics & Finance', 'Computer Science and Philosophy', 'Computer Science and Music',
                       'Computer Science and Linguistics',
                       'Computer Science and Geography & Geographic Information Science',
                       'Computer Science and Economics', 'Computer Science and Crop Sciences',
                       'Computer Science and Chemistry',
                       'Computer Science and Astronomy', 'Computer Science and Anthropology',
                       'Computer Science and Animal Sciences',
                       'Computer Science and Advertising', 'Computer Science', 'Computer Engineering',
                       'Comparative and World Literature', 'Community Health', 'Communication', 'Classics',
                       'Civil Engineering',
                       'Chemistry', 'Chemical Engineering', 'Brain and Cognitive Sciences', 'Biology', 'Bioengineering',
                       'Biochemistry', 'Atmospheric Sciences', 'Astronomy', 'Asian American Studies',
                       'Arts and Entertainment Technology', 'Art Education (K-12)', 'Art and Art History',
                       'Architectural Studies',
                       'Anthropology', 'Animal Sciences', 'Agricultural Leadership, Education, and Communications',
                       'Agricultural Education', 'Agricultural Communications - Journalism',
                       'Agricultural Communications - Advertising', 'Agricultural and Consumer Economics',
                       'Agricultural and Biological Engineering (ENG)',
                       'Agricultural and Biological Engineering (ACES)',
                       'Agribusiness, Markets & Management', 'Agri-Accounting', 'African American Studies',
                       'Aerospace Engineering',
                       'Advertising', 'Actuarial Science', 'Acting', 'ACES Undeclared', 'Accountancy']))
